// Default site content and static assets loaded before the renderer in index.html.
const PH="assets/jesse-stallsworth.jpg",K="jbs_site_v1";
const DEF={name:"Jesse B. Stallsworth, MS, QMPR-C, CPER",role:"Academic Technology Leader",loc:"Lexington, KY",
sum:"Forward-thinking academic technology leader with a strong higher education foundation, specializing in scalable learning solutions that drive student success. Proven track record of aligning instructional technology with institutional goals, collaborating with stakeholders to enhance learning outcomes, and driving continuous academic improvement.",
about:"I’ve built my career around helping people get more from the tools they use to teach, learn, and work. I started in instructional design and higher education, where I saw how thoughtful technology can make a real difference in someone’s day. Since then, my work has grown to include leading teams, improving services, and finding practical ways to bring new tools like AI into the mix. I enjoy taking a complicated challenge, listening to the people closest to it, and working with them to make things clearer and easier. I’m based in Lexington, Kentucky, and I’m always curious about what we can make better next.",
stats:[["14+","Years of Combined Academic and Information Technology Experience"],["50%","Increase in Cost Savings and Faster Support"],["10+","Rising Technology Professionals Mentored"],["200+","Pieces of Multimedia and Interactive Content Created"],["345","Students Taught"]],
values:[{t:"Do the Right Thing.",d:"I build relationships on honesty, transparency, and trust."},{t:"Keep It Practical.",d:"The best solution isn't necessarily the most complicated one. I focus on what works."},{t:"Make the Complex Simple.",d:"Technology should empower people—not overwhelm them. I translate complex challenges into clear, understandable solutions."},{t:"Own the Outcome.",d:"I take responsibility for my work and stand behind the solutions I provide."},{t:"People Matter.",d:"Successful technology starts with understanding the people who use it. I put people at the center of the solutions I develop."},{t:"Always Be Learning.",d:"Technology is constantly changing, and I believe in staying curious, adapting, and continually improving."}],
email:"jesse.b.stallsworth@gmail.com",links:[["LinkedIn","https://www.linkedin.com/in/your-profile"],["Bold Profile","https://bold.pro/my/jessebstallsworth"]],
skills:["Application analysis","Application integration","LMS administration","Curriculum development","Instructional design (ADDIE)","AI agents and chatbots","Generative AI and automation","Canvas and Moodle","Customer support","Advanced technical support","Decision-making","Team building and leadership"],
exp:[{d:"07/2026 – Present",r:"Applications Analyst",o:"University of Kentucky Information Technology Services – Beyond Blue",b:["Partner with cross-functional teams to implement software solutions aligned with institutional goals","Streamline application support processes, reducing response times and improving efficiency by 50%","Analyze application data and coordinate with vendors to improve the user experience","Evaluate application functionality and recommend enhancements based on user feedback and system analysis","Develop training materials and lead faculty workshops on application best practices","Evaluate emerging technologies and recommend strategic improvements to application performance","Resolve end-user technical issues and provide responsive application support","Identify cost-saving opportunities worth thousands of dollars by making better use of existing application infrastructure","Manage multiple projects simultaneously to meet timelines and established guidelines"]},
{d:"07/2021 – 07/2026",r:"Director of Instructional Design",o:"University of Kentucky College of Nursing",b:["Led instructional design initiatives from concept through implementation using ADDIE and evidence-based teaching practices","Spearheaded AI adoption across instructional design, simulation, and academic programs","Engineered AI-powered agents and chatbots grounded in institutional knowledge bases to improve service efficiency","Used generative AI and automation tools to streamline academic and operational workflows","Developed learning resources and assessments to support course outcomes and student achievement","Partnered with faculty, clinicians, subject matter experts, and cross-college teams to enhance curricula and pilot AI-enabled learning solutions","Oversaw funding initiatives and technology acquisitions, building strategic partnerships and prioritizing cost-effective solutions","Ensured accessibility, accreditation, institutional policy, and instructional technology standards across academic programs","Addressed complex technical challenges through process improvements and automation"]},
{d:"11/2019 – 07/2021",r:"Instructional Designer",o:"University of Kentucky College of Nursing",b:["Founded the Instructional Design & Innovation Council to support ongoing course improvement","Led the rapid transition from in-person to fully online instruction during COVID-19 and evaluated outcomes","Designed course materials and co-developed curricula for undergraduate and graduate programs","Developed standardized Canvas templates for BSN, MSN, DNP, and Ph.D. programs","Built a Virtual Resource Room that supported successful CCNE accreditation","Created 20+ multimedia learning projects and launched an original career-focused nursing podcast","Evaluated instructional technologies for effectiveness and cost efficiency","Supervised support operations and served as College of Nursing liaison to institutional learning and online education teams"]},
{d:"05/2017 – 07/2019",r:"Director of Operations, CI CoLab",o:"University of Kentucky College of Communication and Information",b:["Led student, faculty, and staff teams working across social media, eye-tracking, distance learning, and virtual reality","Expanded the user-experience lab with four new divisions, including Learning Management and Analytics","Established the CoLab Internship Program and mentored 10+ interns in academic and research technologies","Built campus partnerships to launch research initiatives and expand lab capabilities","Managed complex projects from planning through delivery, aligned with organizational goals","Created policies and procedures to streamline lab operations","Maintained compliance with software license agreements, privacy policies, and institutional standards","Conducted course audits and redesigns for communication and journalism programs"]},
{d:"08/2012 – Present",r:"IT Consultant, Academic and Information Technology",o:"Independent – Lexington, KY",b:["Administer Moodle for a private client and provide tailored instructional technology support","Designed materials for 5+ graduate-level and multiple undergraduate courses","Develop learning experiences to support graduate student engagement and comprehension","Conduct client needs assessments and recommend instructional technologies aligned with operational goals","Advise clients on IT infrastructure strategy, Microsoft Office architecture, and business needs","Create curricula, research topics, and course formats, including subject matter and presentation","Design websites and tailored IT solutions to improve client operations and productivity"]},
{d:"2016 – 2017",r:"Earlier roles",o:"University of Kentucky",b:["Post-Baccalaureate Teaching Assistant (2017)","UK 101/201 Peer Instructor (2016–2017)","Office Assistant, College of Communication and Information (2016)"]}],
edu:[{d:"05/2019",r:"M.S., Information Communication Technology",o:"University of Kentucky",b:["Emphases: Policy and Regulation and Health Informatics","4.0 GPA, top 1% of class","Capstone: Implementing Eye-Tracking Metrics to the Usability Testing of Novel Software and Hardware Deployments"]},
{d:"05/2017",r:"B.S., Information Communication Technology",o:"University of Kentucky",b:["Emphasis: Technology Management","Magna Cum Laude, top 10% of class, Dean's List 2014–2017","Robinson Scholar (full undergraduate scholarship)"]}],
certs:["MagicSchool AI Level IV Certified Educator (2025)","Quality Matters: Seventh Edition Rubric Update (2023)","Quality Matters: Continuing and Professional Education Reviewer (2022)","Quality Matters: Higher Education Peer Reviewer (2021)","Quality Matters: Applying the QM Rubrics (2018)","Kentucky Occupational Skills Standards Assessment, KOSSA (2013)"],
teach:["UK 101 Lead Instructor and NUR 101 Co-Instructor, 2021–2025: first-year experience and pre-nursing mentorship","NUR 520 Fundamentals of Online Teaching, Co-Instructor and Course Designer (Spring 2021)","UK 101/201 Peer Instructor, 2016–2017"],
lead:["Member, University of Kentucky College of Nursing Values Committee, 2025–Present","Member, University of Kentucky Online Education Steering Committee, 2024–Present","Co-Chair, Strategic Planning Innovation Committee, UK College of Nursing, 2024–2026","Co-Chair, Technology Enhancement Council, UK College of Nursing, 2023–2024","Industry Expert, Information and Academic Technology, Business Advisory Committee, Rockcastle County Area Technology Center, 2022–Present","Chair, Vice-Chair, and Past Chair, UK College of Nursing Staff Council, 2022–2025","Co-Chair, Instructional Design Innovation Council, UK College of Nursing, 2020–2023","Member, Work-Life Committee, UK College of Nursing, 2019–2025","Member, Psychology Student Association, UK College of Arts and Sciences, 2019","Student Representative, Dean Search Committee, UK College of Communication and Information, 2019","Chair, Dean's Student Leadership Council (SLC), UK College of Communication and Information, 2017–2019","President, Interim President, Vice-President, and Communications Director, Information Communication Technology Student Association (ICTSA), UK College of Communication and Information, 2016–2019","Student Representative, College of Communication and Information National Advisory Board (NAB), UK College of Communication and Information, 2016–2019","Chair, UK Remembers Planning Committee, 2015"],
awards:["Marquis Who's Who Honored Listee (2024)","UK College of Nursing: Excellence in Support of the College of Nursing (2024)","UK College of Nursing: Staff Member of the Year (2020)","UK College of Nursing: Dean's PUMA Award for Excellence (2020)","UK College of Communication and Information: Maurice A. Clay Award for Leadership, Scholastic Achievement, Conspicuous Attainment, and Service to the College (2017)","UK College of Communication and Information: Multiple Dean's List Honors (2014–2017)","UK Robinson Scholarship: Full Undergraduate Scholarship (2008)"],
int:"Music technology and production, aviculture, aviation science and history, AI and machine learning, animal welfare advocacy, 3D printing, houseplant care",
proj:[{t:"AI Agents and Chatbots",b:["Chatbots built on institutional knowledge bases","Designed to improve service efficiency at the College of Nursing"],l:""},
{t:"Career Podcast: When I Grow Up, I Want to Be…",b:["Original podcast series (2021–2022)","Profiles nursing careers to support student engagement"],l:"https://podcasts.apple.com/us/podcast/when-i-grow-up/id1567267988"},
{t:"Interactive Learning Modules",b:["S-CATS mental health self-checkup","Exam Anxiety Prevention","Preeclampsia learning module","Next-Gen NCLEX simulation pre-work"],l:""},
{t:"Canvas Templates and Virtual Resource Room",b:["Standardized templates for BSN, MSN, DNP, and Ph.D. programs","Resource room supported CCNE accreditation"],l:""},
{t:"Course Reviews based on Quality Matters Standards",b:["Course improvement reviews for NUR 324","Course improvement reviews for NUR 360","Course improvement reviews for NUR 916"],l:""},
{t:"Presentations and Workshops",b:["Lunch & Learns on Canvas, Zoom, YuJa, Flipgrid, and Google Workspace","Talks on eye-tracking and usability","AACN poster on curriculum think tanks"],l:""}],
pubs:[{t:"Interactive modules and study tools (2022–2023)",b:["UK College of Nursing Graduate Program Recruitment Showcase (Mar 2023)","Interactive Accelerated BSN Health Assessment Study Guide (Mar 2023)","Next-Generation NCLEX Questions for Simulation Pre-Work (Jan 2023)","S-CATS: Stopping Crises at the Start, a Mental Health Self-Checkup Tool (Jan 2023)","Exam Anxiety Prevention (Jan 2023)","Medical Mathematics for Obstetric Courses (Oct 2022)","Online Preeclampsia Module (Oct 2022)"]},
{t:"Videos and software simulations",b:["APP/Preceptor Guide to Student Documentation in EPIC (Dec 2022)","Student Guide to Student Documentation in EPIC (Dec 2022)","Creating Your Portfolio in Digication (Dec 2021)","Uploading Documents to Digication (Dec 2021)","Digication Assignment Submission (Dec 2021)"]},
{t:"Quality course improvement reviews",b:["NUR 360: Professional Communication in Nursing Practice (Sep 2022)","NUR 916: Program Planning and Evaluation for Improvement in Practice and Health Outcomes (Jan 2022)","NUR 324: Fundamentals of Adult Nursing Care for Accelerated BSN Students (Oct 2021)"]},
{t:"Podcast: When I Grow Up, I Want to Be… (2021–2022)",b:["An Advanced Practice Registered Nurse (Jun 2022)", "A Hospice Nurse (Jun 2022)", "A Pediatric Nurse Practitioner (Jun 2022)", "A Certified Nurse Midwife (Jun 2022)", "An Operating Room Nurse (Jun 2022)", "A Nurse Entrepreneur (May 2022)", "A Psychiatric/Mental Health Nurse Practitioner (May 2022)", "A Dean of Nursing (May 2022)", "An Occupational Health Nurse (May 2022)", "A Nurse Innovator (May 2022)", "A Certified Nurse Anesthetist (Aug 2021)", "A Flight Nurse (Jun 2021)", "A Wound Ostomy Continence Nurse (Jun 2021)", "An ER Nurse (Jun 2021)", "A Nurse Scientist (May 2021)", "A Maternal and Child Health Advocate (May 2021)", "A Public Health Advocate (Sep 2021)", "A VP of Hospital Operations (Sep 2020)", "Series teaser"],u:["https://podcasts.apple.com/us/podcast/episode-16-an-advanced-practice-registered-nurse-with/id1567267988?i=1000565225751", "https://podcasts.apple.com/us/podcast/episode-15-a-hospice-and-palliative-care-nurse/id1567267988?i=1000565225408", "https://podcasts.apple.com/us/podcast/episode-14-a-pediatric-nurse-practitioner-with-dr/id1567267988?i=1000565225583", "https://podcasts.apple.com/us/podcast/episode-13-a-certified-nurse-midwife-with-sabrina-tucker/id1567267988?i=1000565225616", "https://podcasts.apple.com/us/podcast/episode-12-an-operating-room-nurse-with-kim-farris/id1567267988?i=1000565224036", "https://podcasts.apple.com/us/podcast/episode-11-a-nurse-entrepreneur-with-dr-rebecca-dekker/id1567267988?i=1000564239142", "https://podcasts.apple.com/us/podcast/episode-10-a-psychiatric-mental-health-nurse/id1567267988?i=1000564232964", "https://podcasts.apple.com/us/podcast/episode-9-a-dean-of-nursing-with-dr-janie-heath/id1567267988?i=1000564232965", "https://podcasts.apple.com/us/podcast/episode-8-an-occupational-health-nurse-with-dr-debbie-reed/id1567267988?i=1000564232891", "https://podcasts.apple.com/us/podcast/episode-7-a-nurse-innovator-with-dr-nicole-garritano/id1567267988?i=1000564233030", "https://podcasts.apple.com/us/podcast/episode-6-a-crna-with-mary-ellen-loyall/id1567267988?i=1000531845042", "https://podcasts.apple.com/us/podcast/episode-5-a-flight-nurse-with-ryan-pratt/id1567267988?i=1000525767923", "https://podcasts.apple.com/us/podcast/episode-4-a-wound-ostomy-continence-nurse-with/id1567267988?i=1000524833424", "https://podcasts.apple.com/us/podcast/episode-3-an-emergency-department-nurse-with-dr-patti/id1567267988?i=1000523938551", "https://podcasts.apple.com/us/podcast/episode-2-a-nurse-scientist-with-dr-jake-higgins/id1567267988?i=1000523208747", "https://podcasts.apple.com/us/podcast/episode-1-a-maternal-and-child-health-advocate/id1567267988?i=1000521625452", "", "", "https://podcasts.apple.com/us/podcast/teaser/id1567267988?i=1000521489515"]},
{t:"Presentations and posters, College of Nursing (2020–2022)",b:["Quality Matters Basics (Mar 2022)","Increasing Student Engagement Using Advanced Zoom Features, Lunch & Learn (May 2021)","Canvas New Quizzes Fundamentals and Refresher, Lunch & Learn (Jan 2021)","Innovating Online Course Delivery Through Nursing Curriculum Think Tanks, AACN Fall Faculty Conference poster (Dec 2020)","G-Suite for Education, Lunch & Learn (Dec 2020)","YuJa Media Basics (Sep 2020)","Introduction to Flipgrid, Lunch & Learn (Jan 2020)"]},
{t:"Research, talks, and lectures (2017–2019)",b:["Implementing Eye-Tracking Metrics to the Usability of Novel Software and Hardware Deployments, master's paper and poster defense (May 2019)","Social Media Listening and Analytics (Apr 2019)","Content Development and Analysis for the Gaming Industry, guest lecture (2019)","The TAM Model in Usability Testing (2019)","What Is Eye-Tracking? How Can It Help Me? (2019)","Eye-Tracking in Instructional Design (2019)","Web Usability Standards and Their Importance (2019)","Eye-Tracking in Course Design and Education (2019)","Welcome to VR! Presentation and demonstration, UK Libraries (2018)","Academic and Empirical Usability Testing (2018)","Learning Management: Pain Points and Pain Pills, UK ITS Online Teaching Toolkit (2018)","Eye-Tracking in Media Research (2018)","A Literature Review of Usability Testing Methodologies, baccalaureate paper (May 2017)","Designing a Usable Product, guest lecture (2017)","Designing a Survey to Collect Customer Feedback, guest lecture (2017)"]}],
acc:[],accIntro:"",ints:["Multi-instrumentalist","Music technology and production","Aviculture","Aviation science and history","Artificial intelligence and machine learning","Animal welfare advocacy","3D printing","Houseplant care"],tests:[{q:"Add a testimonial from a colleague, client, or student here.",n:"Name",r:"Title, Organization"}]};
const GL=["✦","◉","▣","❖","✓","▶"];
const ADD={ints:"New interest",acc:{m:"00%",t:"Accomplishment title",d:"Describe the result and your role.",l:""},pubs:{t:"New category",b:["New item"]},proj:{g:"◆",t:"New project",b:["Describe the project."],l:""},tests:{q:"Quote",n:"Name",r:"Title, Organization"},certs:"New item",awards:"New item",lead:"New item",exp:{d:"Dates",r:"Role",o:"Organization",b:["Detail"]}};

const BIO=[
"Hi, I’m Jesse—a higher education and academic technology leader, consultant, and partner to organizations and individuals working through the opportunities and challenges of a changing technology landscape. I bring more than 14 years of combined experience in academic and information technology, with a career centered on helping people use technology with purpose, confidence, and care.",
"Much of my full-time work has been alongside faculty and academic teams. I help educators strengthen their teaching, make informed choices about digital tools, and bring new learning methods into practice. That can mean planning a technology-supported course, improving an established teaching approach, or helping a team work through the unexpected issues that arise when new tools and processes meet real classroom needs. I aim to make those transitions practical and manageable, so faculty can focus on what matters most: creating meaningful learning experiences for students.",
"My consulting work extends that same people-centered approach to institutions, teams, and individual clients. I listen closely to understand their goals, constraints, and context, then help identify solutions that are realistic, sustainable, and aligned with the people who will use them. I value clear communication, thoughtful planning, and collaboration at every stage—from exploring possibilities to implementation and ongoing improvement.",
"I also believe the future of technology, including artificial intelligence, depends on how thoughtfully we put it to work. AI should work with people, not instead of them. It can help us explore ideas, reduce repetitive tasks, and make information more accessible, while people remain essential for judgment, creativity, empathy, and accountability. The goal is not simply to adopt new technology, but to use it in ways that strengthen human capabilities and improve the work we do together.",
"My mission is to help clients, companies, and academic institutions accomplish meaningful goals through academic and information technology—building confidence, supporting innovation, and creating solutions that serve people and make a lasting difference."
];

const TEACHING_COURSES=[
{y:"2025",s:"Fall",c:"UK 101: Academic Orientation",r:"Lead Instructor",h:1,n:30},
{y:"2024",s:"Fall",c:"UK 101: Academic Orientation",r:"Lead Instructor",h:1,n:29},
{y:"2023",s:"Fall",c:"NUR 101: Academic Orientation and Introduction to Nursing",r:"Co-Instructor",h:1,n:39},
{y:"2022",s:"Fall",c:"NUR 101: Academic Orientation and Introduction to Nursing",r:"Co-Instructor",h:1,n:45},
{y:"2021",s:"Fall",c:"NUR 101: Academic Orientation and Introduction to Nursing",r:"Co-Instructor",h:1,n:41},
{y:"2021",s:"Spring",c:"NUR 520: Fundamentals of Online Teaching",r:"Co-Instructor / Course Designer",h:3,n:6},
{y:"2017",s:"Fall",c:"UK 101: Academic Orientation",r:"Peer Instructor",h:1,n:35},
{y:"2017",s:"Spring",c:"UK 201: Academic Orientation for Transfers",r:"Peer Instructor",h:2,n:35},
{y:"2016",s:"Fall",c:"UK 101: Academic Orientation",r:"Peer Instructor",h:1,n:25},
{y:"2016",s:"Summer",c:"UK 101: Academic Orientation",r:"Peer Instructor",h:1,n:20},
{y:"2016",s:"Spring",c:"UK 101: Academic Orientation",r:"Peer Instructor",h:1,n:40}
];
const TEACHING_ROLES=[
{r:"UK 101 Lead Instructor and NUR 101 Co-Instructor",d:"2021–2025",o:"University of Kentucky"},
{r:"NUR 520 Co-Instructor and Course Designer",d:"Spring 2021",o:"Fundamentals of Online Teaching"},
{r:"Post-Baccalaureate Teaching Assistant",d:"August 2016–May 2017",o:"University of Kentucky Student and Academic Life"},
{r:"UK 101/201 Peer Instructor",d:"2016–2017",o:"University of Kentucky"}
];
const CAPSTONE_URL="https://www.dropbox.com/scl/fi/kzwlb54ox56e0d6dzty0w/Implementing-Eye-Tracking-Metrics-to-The-Usability-Testing-of-Novel-Software-and-Hardware-Deployments..pdf?rlkey=fdyrysubk3zbttwqhvr1dcmj7&st=dsp4o0ee&dl=0";
